CREATE DATABASE readable;

CREATE ROLE readable WITH LOGIN PASSWORD '';

-- \c readable;

CREATE EXTENSION IF NOT EXISTS vector;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO readable;
