name: Production

on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Build
    runs-on: linux-arm64-2vcpu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::637423633734:role/actions@github
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: 637423633734.dkr.ecr.ap-northeast-2.amazonaws.com/readable
          tags: type=raw,value=latest

      - name: Build image
        uses: docker/build-push-action@v5
        id: build
        with:
          push: true
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=637423633734.dkr.ecr.ap-northeast-2.amazonaws.com/readable:cache
          cache-to: type=registry,ref=637423633734.dkr.ecr.ap-northeast-2.amazonaws.com/readable:cache,mode=max,image-manifest=true
          provenance: false
